<?php
// This is Zarilia language file.
// This file was modified generated by Zarilia on Mon, 05 Jun 2006 13:54:07 +0100
// define("_MD_AVATARMAN","Avatar Manager");

define( "_MA_AD_AVATAR_ID", "#" );
define( "_MA_AD_AVATAR_NAME", "Name" );
define( "_MA_AD_AVATAR_FILENAME", "Avatars" );
define( "_MA_AD_AVATAR_MIMETYPE", "Mimetype" );
define( "_MA_AD_AVATAR_CREATED", "Created" );
define( "_MA_AD_AVATAR_WEIGHT", "Weight" );
define( "_MA_AD_AVATAR_DISPLAY", "Display" );
define( "_MA_AD_AVATAR_UPLOADED", "Uploaded" );
define( "_MA_AD_AVATAR_UID", "Owner" );
define( "_MA_AD_AVATAR_UP", "Uploader" );

define( "_MA_AD_EAVATAR_CREATE", "Create Avatar" );
define( "_MA_AD_EAVATAR_MODIFY", "Modify Avatar" );

define( "_MA_AD_EAVATAR_NAME", "Name:" );
define( "_MA_AD_EAVATAR_NAME_DSC", "Select a friendly name to be used with this Avatar." );
define( "_MA_AD_EAVATAR_FILE", "Upload File:" );
define( "_MA_AD_EAVATAR_FILE_DSC", "Please select a file to upload.<br /><br />Max Filesize: <b>%s</b> kb<br />Max Filewidth: <b>%spx</b> <br />Max Fileheight: <b>%spx</b>" );
define( "_MA_AD_EAVATAR_WEIGHT", "Weight:" );
define( "_MA_AD_EAVATAR_WEIGHT_DSC", "Select the display position of this Avatar." );
define( "_MA_AD_EAVATAR_DISPLAY", "Display Avatar?" );
define( "_MA_AD_EAVATAR_DISPLAY_DSC", "Select to display Avatar in Avatar listing." );
define( "_MA_AD_EAVATAR_DWEIGHT", "Default Weight:" );
define( "_MA_AD_EAVATAR_DWEIGHT_DSC", "Enter default weight for all selected Avatars." );
define( "_MA_AD_EAVATAR_AUTOWEIGHT", "Use Auto Weight?" );
define( "_MA_AD_EAVATAR_AUTOWEIGHT_DSC", "Use automatic weight overriding 'Default weight' option." );
define( "_MA_AD_EAVATAR_SELECTIMAGE", "Select Avatar Image:" );
define( "_MA_AD_EAVATAR_SELECTIMAGE_DSC", "" );
/*
*/
define( "_MA_AD_EAVATAR_BATCH", "Batch Upload" );
define( "_MA_AD_EAVATAR_NOTHINGUPLOAD", "No Images Found In Cache" );
define( "_MA_AD_EAVATAR_BATCHAVATARS", "Upload Batch Avatars:" );
define( "_MA_AD_EAVATAR_BATCHAVATARS_DSC", "Select items to upload or delete. (if the delete file option has been selected)" );
define( "_MA_AD_EAVATAR_DELETE", "Delete all selected items." );
define( "_MA_AD_EAVATAR_DELETE_DSC", "Use this option to delete items from the image list. All other options will be ignored." );

define( "_MD_AD_SYSAVATARS", "System Avatars" );
define( "_MD_AD_CSTAVATARS", "Custom Avatars" );

define( "_FAILSAVEIMG_UPLOADPATH", "<b>Save Failed:</b>Upload path does not exist or is not writeable! (%s)." );
define( "_FAILSAVEIMG_UPLOADIMAGE", "<b>Save Failed:</b> Image '%s' does not exist or is not writeable! (%s)." );
define( "_FAILSAVEIMG_UPLOADSIZE", "<b>Save Failed:</b> Image '%s' is larger than permitted size. Actual: %s Allowed: %s." );
define( "_FAILSAVEIMG_UPLOADDEM", "<b>Save Failed:</b> Image '%s'dimensions are larger than permitted sizes. Filesize: %sx%s Actual: %sx%s." );
define( "_FAILSAVEIMG_UPLOADMIME", "<b>Save Failed:</b> Image '%s' mimetype is not permitted. (%s)" );
define( "_FAILSAVEIMG_UPLOADCOPY", "<b>Save Failed:</b> Could not copy %s to destination folder." );
define( "_FAILSAVEIMG_DATABASE", "<b>Save Failed:</b> Could not save information to database" );

define( "_MA_AD_AVATAR_DISPLAYAMOUNT", "Display Amount" );
define( "_MA_AD_EAVATAR_OPTIMIZE", "Optimize Database Table" );
define( "_MA_AD_EAVATAR_EMPTY", "Empty Database" );

/*Addons Information*/
define( '_MA_INFO_NAME', 'Avatar Administration' );
define( '_MA_INFO_DESCRIPTION', '' );
define( '_MA_INFO_AUTHOR', 'Zarilia Project' );
define( '_MA_INFO_LICENSE', 'GPL see LICENSE' );
define( '_MA_INFO_IMAGE', 'avatar_admin.png' );

define( '_MA_INFO_LEAD', 'John Neill, Raimondas Rimkevicius' );
define( '_MA_INFO_CONTRIBUTORS', '' );
define( '_MA_INFO_CREDITS', 'Zarilia Project' );
define( '_MA_INFO_WEBSITE_URL', 'http://zarilia.com' );
define( '_MA_INFO_WEBSITE_NAME', 'Zarilia Project' );
define( '_MA_INFO_EMAIL', 'webmaster@zarilia.com' );
define( '_MA_INFO_VERSION', '1.0' );
define( '_MA_INFO_STATUS', 'Alpha' );
define( '_MA_INFO_RELEASEDATE', 'Not Yet' );
define( '_MA_INFO_DISCLAIMER', 'This is a alpha product and not to be used on a production website' );

define( '_MA_INFO_DEMO_SITE_URL', 'http://zarilia.com' );
define( '_MA_INFO_DEMO_SITE_NAME', 'Zarilia Demo' );
define( '_MA_INFO_SUPPORT_SITE_URL', 'http://zarilia.com' );
define( '_MA_INFO_SUPPORT_SITE_NAME', 'Zarilia Support Site' );
define( '_MA_INFO_SUBMIT_BUG_URL', 'http://sourceforge.net/tracker/?group_id=140225&atid=745776' );
define( '_MA_INFO_SUBMIT_BUG_NAME', 'Zarilia Bug Tracker' );
define( '_MA_INFO_SUBMIT_FEATURE_URL', 'http://sourceforge.net/tracker/?group_id=140225&atid=745779' );
define( '_MA_INFO_SUBMIT_FEATURE_NAME', 'Zarilia Feature Tracker' );
define( '_MA_INFO_PATH', 'index.php?fct=avatars' );
define( '_MA_INFO_OFFICIAL', 1 );
define( '_MA_INFO_SYSTEM', 1 );
define( '_MA_INFO_HASADMIN', 1 );

?>